---
title: digitalWrite()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---


//
:ext-relative: .html

= digitalWrite()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Scrive il valore `HIGH` o `LOW` in un pin digitale.

Se il pin è stato configurato come `OUTPUT` con `pinMode()`, la sua tensione sarà impostata sul valore corrispondente: 5V (o 3,3V nelle schede a 3,3V) per `HIGH`, 0V (massa) per `LOW`.
[%hardbreaks]

Se il pin è configurato come `INPUT`, `digitalWrite()` abilita (`HIGH`) o disabilita (`LOW`) il pullup interno sul pin di ingresso. Si consiglia di impostare `pinMode()` su `INPUT_PULLUP` per abilitare la resistenza di pull-up interna. Per ulteriori informazioni, consultare il tutorial sui pin digitali.
[%hardbreaks]

Se non si imposta `pinMode()` su `OUTPUT` e si collega un LED a un pin, quando si richiama `digitalWrite(HIGH)`, il LED potrebbe apparire poco luminoso. Senza impostare esplicitamente `pinMode()`, `digitalWrite()` avrà attivato la resistenza di pull-up interna, che agisce come una resistenza che limita la corrente.
[%hardbreaks]

[float]
=== Sintassi
`digitalWrite(pin, valore)`


[float]
=== Parametri
`pin`: il numero del pin

`valore`: `HIGH` o `LOW`

[float]
=== Restituisce
Nulla

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di esempio
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Il codice rende il pin digitale 13 un `OUTPUT` e lo alterna tra `HIGH` e `LOW` a intervalli di un secondo.

//[source,arduino]
----
void setup()
{
  pinMode(13, OUTPUT);          // imposta il pin 13 come uscita
}

void loop()
{
  digitalWrite(13, HIGH);       // imposta il pin digitale 13 a livello alto
  delay(1000);                  // attende un secondo
  digitalWrite(13, LOW);        // imposta il pin digitale 13 a livello basso
  delay(1000);                  // attende un secondo
}
----
[%hardbreaks]

[float]
=== Note e avvertenze
I pin di ingresso analogici possono essere utilizzati come pin digitali, denominati A0, A1, ecc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Vedi anche

[role="example"]
* #EXAMPLE# http://arduino.cc/it/Tutorial/DigitalPins[Tutorial: Digital Pins]

--
// SEE ALSO SECTION ENDS
