---
title: digitalRead()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---


//
:ext-relative: .html

= digitalRead()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Legge il valore di un pin digitale specificato, di tipo `HIGH` o `LOW`.
[%hardbreaks]


[float]
=== Sintassi
`digitalRead(pin)`


[float]
=== Parametri
`pin`: il numero del pin digitale da leggere

[float]
=== Restituisce
`HIGH` o `LOW`

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di esempio
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Imposta il pin 13 sullo stesso valore del pin 7, definito come ingresso.

//[source,arduino]
----
int ledPin = 13;   // LED collegato al pin digitale 13
int inPin = 7;     // pulsante connesso al pin digitale 7
int val = 0;       // variabile che memorizza il valore letto

void setup()
{
  pinMode(ledPin, OUTPUT);      // imposta il pin digitale 13 come uscita
  pinMode(inPin, INPUT);        // imposta il pin digitale 7 come ingresso
}

void loop()
{
  val = digitalRead(inPin);     // legge il pin di ingresso
  digitalWrite(ledPin, val);    // imposta il LED sul valore del pulsante
}
----
[%hardbreaks]

[float]
=== Note e avvertenze
Se il pin non è connesso a qualcosa, digitalRead() può restituire HIGH o LOW (e questo può variare casualmente).

I pin di ingresso analogici possono essere utilizzati come pin digitali, indicati come A0, A1, ecc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Vedi anche

[role="example"]
* #EXAMPLE# Tutorial: (http://arduino.cc/it/Tutorial/DigitalPins[Digital Pins])

--
// SEE ALSO SECTION ENDS
