---
title: pinMode()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---


//
:ext-relative: .html

= pinMode()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Configura il pin specificato in modo che si comporti come ingresso o come uscita. Per informazioni dettagliate sulla funzionalità dei pin, vedere la descrizione di (http://arduino.cc/it/Tutorial/DigitalPins[digital pins]).
[%hardbreaks]
A partire da Arduino 1.0.1, è possibile abilitare le resistenze di pullup interne con la modalità INPUT_PULLUP. Inoltre, la modalità INPUT disabilita esplicitamente i pullup interni.
[%hardbreaks]


[float]
=== Sintassi
`pinMode(pin, funzionamento)`


[float]
=== Parametri
`pin`: il numero del pin di cui si vuole impostare il funzionamento

`INPUT`, `OUTPUT` o `INPUT_PULLUP`. (per una descrizione più completa della funzionalità, consultare la pagina (http://arduino.cc/it/Tutorial/DigitalPins[digital pins])).

[float]
=== Restituisce
Nulla

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di esempio
Il codice rende il pin digitale 13 un `OUTPUT` e lo alterna tra `HIGH` e `LOW`

//[source,arduino]
----
void setup()
{
  pinMode(13, OUTPUT);          // imposta il pin 13 come uscita
}

void loop()
{
  digitalWrite(13, HIGH);       // imposta il pin digitale 13 a livello alto
  delay(1000);                  // attende un secondo
  digitalWrite(13, LOW);        // imposta il pin digitale 13 a livello basso
  delay(1000);                  // attende un secondo
}
----
[%hardbreaks]

[float]
=== Note e avvertenze
I pin di ingresso analogici possono essere utilizzati come pin digitali, denominati A0, A1, ecc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Vedi anche

[role="example"]
* #EXAMPLE# http://arduino.cc/it/Tutorial/DigitalPins[Descrizione dei pin della scheda Arduino^]

--
// SEE ALSO SECTION ENDS
