= Reference-it

Reference-it è il repository per la documentazione di rifermento del linguaggio per sintassi di Arduino in **Italiano** +
Tutti i file dei termini di riferimento sono in formato AsciiDoc.

Grazie per aver speso del tempo per contribuire al contenuto di Arduino, questo è davvero d'aiuto per l'intera Community di Arduino.

== Creazione del contenuto e modifica

Se vuoi contribuire con nuovi contenuti, crea un nuovo file (con qualunque editor di testo) e salvalo con estensione .adoc

Non usare parentesi oppure caratteri speciali nel nome del file. In https://raw.githubusercontent.com/arduino/reference-it/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc[`reference-it/AsciiDoc_sample/AsciiDoc_Dictionary`] troverai una panoramica della sintassi AsciiDoc. Questo include Titoli, Testo, Link, Immagini, Tabelle, Codice e varie integrazioni (video, slideshow, audio e codice). Puoi vederlo renderizzato https://https://www.arduino.cc/reference/it/asciidoc_sample/asciidoc_dictionary/asciidoc_template-dictionary/[qui].

Se vuoi contribuire alla Language Reference o modificare contenuto esistente, puoi trovare due modelli in reference-it/AsciiDoc_sample/Reference_Terms:

* Usa https://raw.githubusercontent.com/arduino/reference-it/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Single_Entity.adoc[`AsciiDoc_Template-Single_Entity.adoc`] (renderizzato https://www.arduino.cc/reference/it/asciidoc_sample/reference_terms/asciidoc_template-single_entity/[qui]) per termini come link:http://arduino.cc/en/Reference/AnalogWrite[analogWrite].
* Usa https://raw.githubusercontent.com/arduino/reference-it/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Parent_Of_Entities.adoc[`AsciiDoc_Template-Parent_Of_Entities.adoc`] (renderizzato https://www.arduino.cc/reference/it/asciidoc_sample/reference_terms/asciidoc_template-parent_of_entities/[qui]) per gruppi di funzioni come link:http://arduino.cc/en/Reference/Serial[Serial].

Nota che ogni file della Reference dovrebbe includere almeno una Descrizione, del Codice di Esempio, e link ad altre informazioni rilevanti ( Vedi la sezione Altro ).

Se hai bisogno di aggiungere immagini ad Asciidoc crea una cartella chiamata attachments nella stessa directory del file Asciidoc. Le immagini possono essere salvate in formato SVG e PNG, dimesione massima: 200KB.

== Contribuisci al contenuto su Github
Se non hai familiarità con Git puoi contribuire direttamente su Github attraverso la loro interfaccia online. Abbiamo creato un breve Tutorial per mostrarti come, https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37[DAI UN' OCCHIATA!]

link:https://help.github.com/articles/editing-files-in-another-user-s-repository/[Puoi anche seguire questa guida] ( scritta dal team di Github ) per imparare come modificare un file .adoc e proporre una modifica al team di Arduino.

Quando suggerisci una modifica, perfavore segui le linee guida descritte nei Reference template files.


== Inviare una pull request
Siamo lieti che tu voglia contribuire alla Arduino Reference: questo è il modo migliore di aiutare la community.

Il tuo contributo aggiunge o modifica codice esistente oppure descrizioni complete, per favore fai sempre riferimento ad una Issue esistente oppure aprine una nuova prima di contribuire.

Tieni presente che il tuo contributo alla Arduino Reference è sotto una licenza Creative Commons Attribution-Share Alike 3.0 . vedi https://creativecommons.org/licenses/by-sa/3.0/

=== Struttura delle cartelle
[source]
----
reference-it
├─ AsciiDoc_sample
│   ├── AsciiDoc_Dictionary
│   │   ├── AsciiDoc_Template-Dictionary.adoc
│   │   └── attachments
│   └── Reference_Terms
│       ├── AsciiDoc_Template-Parent_Of_Entities.adoc
│       ├── AsciiDoc_Template-Single_Entity.adoc
│       └── attachments
├── Language
│   ├── Functions
│   ├── Structure
│   └── Variables
├── LICENCE.md
└── README.adoc

----

Nella cartella Language, l'albero dei file segue la stessa struttura della link:https://www.arduino.cc/reference/en[Pagina web Arduino Reference]
