---
title: analogRead()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---




= analogRead()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Legge il valore dal pin analogico specificato.

La scheda Arduino contiene un convertitore analogico/digitale a 6 canali ( 8 canali su Arduino Mini e Nano, 16 su Arduino Mega ), a 10 bit.
Questo significa che mapperà le tensioni in ingresso tra 0 e 5 volt usando valori interi compresi tra 0 e 1023.
Questo porta a una risoluzione tra le letture di: 5 volt / 1024 con una risoluzione di 0.0049 volt ( 4.9 mV ) per unità.
L'intervallo delle tensioni in ingresso e la risoluzione possono essere cambiate usando link:../analogreference[analogReference()].

Occorrono circa 100 microsecondi ( 0.0001 s ) per leggere un ingresso analogico, quindi la massima velocità di lettura è circa 10,000 letture al secondo.
[%hardbreaks]


[float]
=== Sintassi

`analogRead( pin )`

[float]
=== Parametri
`pin`: il numero del pin analogico da cui leggere ( da 0 a 5 V su molte schede, da 0 a 7 V su Mini e Nano, da 0 a 15 V su Mega )

[float]
=== Restituisce
int( 0 a 1023 )

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di Esempio
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Il codice legge la tensione su analogPin e la visualizza.

[source,arduino]
----
int analogPin = A3;     // manopola del potenziometro (terminale centrale) connessa ad A3
                        // terminali esterni connessi a massa e +5V
int val = 0;            // variabile per conservare il valore letto

void setup()
{
  Serial.begin(9600);              // inizializza la linea seriale
}

void loop()
{
  val = analogRead(analogPin);     // legge il pin di input
  Serial.println(val);             // visualizza il valore sul monitor seriale
}
----
[%hardbreaks]

[float]
=== Note e Avvertimenti
Se il pin analogico non è connesso, il valore restituito da analogRead() fluttuerà in base a un numero di fattori ( come il valore di altri input analogici, la vicinanza della mano alla scheda, ecc... ).

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Vedi anche

[role="language"]
* #LINGUAGGIO# link:../../zero-due-mkr-family/analogreadresolution[analogReadResolution()]
* #LINGUAGGIO# https://www.arduino.cc/en/Tutorial/AnalogInputPins[Tutorial: Analog Input Pins]
--
// SEE ALSO SECTION ENDS
