---
title: analogReference()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---


//


= analogReference()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Configura la tensione di riferimento usata per gli input analogici ( il valore usato come massima tensione in ingresso ). Le opzioni sono:

* DEFAULT: il riferimento di default di 5 volt ( sulle schede Arduino a 5V ) o 3.3 volt ( sulle schede Arduino a 3.3V )
* INTERNAL: un riferimento integrato, equivalente a 1.1 volt sull' ATmega168 o ATmega328P e 2.56 volt sull' ATmega8 ( non disponibile sull'Arduino Mega )
* INTERNAL1V1: un riferimento integrato a 1.1V ( solo Arduino Mega )
* INTERNAL2V56: un riferimento integrato a 2.56V ( solo Arduino Mega )
* EXTERNAL: la tensione applicata al pin AREF ( solo da 0 a 5V ) viene usata come riferimento

[%hardbreaks]


[float]
=== Sintassi
`analogReference( tipo )`


[float]
=== Parametri
`tipo`: quale tipo di riferimento usare (DEFAULT, INTERNAL, INTERNAL1V1, INTERNAL2V56, o EXTERNAL).

[float]
=== Restituisce
Nulla

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Note e Avvertimenti
Dopo aver cambiato il riferimento, le prime letture da `analogRead()` potrebbero non essere accurate.

*Non usare niente di inferiore a 0V o maggiore di 5V per la tensione di riferimento esterna sul pin AREF! Se stai usando un riferimento esterno sul pin AREF, devi impostare il riferimento a EXTERNAL prima di chiamare `analogRead()`.* Altrimenti, metterai in corto la tensione di riferimeto attiva ( generata internamente ) e il pin AREF, con la possibilità di danneggiare il microcontrollore della tua scheda Arduino.

Alternativamente, puoi collegare la tensione di riferimento esterna al pin AREF attraverso un resitore da 5K, permettendoti di cambiare tra riferimento esterno ed interno. Nota che il resistore altererà la tensione che viene usata come riferimento poichè c'e un resistore interno da 32K sul pin AREF. I due agiscono come un partitore di tensione, quindi, per esempio, 2.5V applicati attraverso un resitore comporteranno 2.5 * 32 / (32 + 5) = ~2.2V sul pin AREF.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Vedi anche

[role="example"]
* #ESEMPIO# http://arduino.cc/en/Tutorial/AnalogInputPins[Descrizione di pin di input analogico]

--
// SEE ALSO SECTION ENDS
