---
title: map()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= map(value, fromLow, fromHigh, toLow, toHigh)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Riassegna un numero da un intervallo a un altro. Ovvero, il valore di *fromLow* viene mappato in *toLow*, il valore di *fromHigh* in *toHigh*, i valori intermedi in valori intermedi, ecc.

Non vincola i valori all'interno dell'intervallo, perché talvolta sono previsti e utili valori esterni all'intervallo. La funzione `constrain()` può essere utilizzata prima o dopo questa funzione, se si desidera limitare gli intervalli.

Si noti che i "limiti inferiori" di un intervallo possono essere più grandi o più piccoli dei "limiti superiori", quindi la funzione `map()` può essere utilizzata per invertire un intervallo di numeri, per esempio

`y = map(x, 1, 50, 50, 1);`

La funzione gestisce correttamente anche numeri negativi, come in questo esempio

`y = map(x, 1, 50, 50, -100);`

che è valido e funziona correttamente.

La funzione `map()` utilizza numeri interi, pertanto non genera frazioni, anche se il calcolo potrebbe generarli. I resti frazionari vengono troncati e non vengono arrotondati o mediati.
[%hardbreaks]


[float]
=== Sintassi



[float]
=== Parametri
`value`: il numero da mappare

`fromLow`: il limite inferiore dell'intervallo corrente del valore

`fromHigh`: il limite superiore dell'intervallo attuale del valore

`toLow`: il limite inferiore dell'intervallo di destinazione del valore

`toHigh`: il limite superiore dell'intervallo di destinazione del valore

[float]
=== Restituisce
Il valore mappato.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di esempio
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
/* Mappa un valore analogico a 8 bit (da 0 a 255) */
void setup() {}

void loop()
{
  int val = analogRead(0);
  val = map(val, 0, 1023, 0, 255);
  analogWrite(9, val);
}
----
[%hardbreaks]

[float]
=== Appendice

Per i matematici, ecco la funzione completa

[source,arduino]
----
long map(long x, long in_min, long in_max, long out_min, long out_max)
{
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
----

--
// HOW TO USE SECTION ENDS
