---
title: max()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= max(x, y)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Calcola il massimo di due numeri.
[%hardbreaks]


[float]
=== Sintassi
`max(x, y)`


[float]
=== Parametri
`x`: il primo numero, qualsiasi tipo di dati
`y`: il secondo numero, qualsiasi tipo di dati

[float]
=== Restituisce
Il maggiore dei due valori.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di esempio
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Il codice garantisce che sensVal sia pari almeno a 20.

[source,arduino]
----
sensVal = max(senVal, 20); // assegna a sensVal il valore maggiore tra sensVal e 20
                           // (garantendo di fatto che sia almeno 20)
----
[%hardbreaks]

[float]
=== Note e avvertenze
Per quanto possa essere controintuitivo, `max()` viene spesso utilizzato per limitare l'estremo inferiore dell'intervallo di una variabile, mentre `min()` viene utilizzato per limitare l'estremo superiore di un intervallo.

Per via del modo in cui la funzione `max()` è implementata, è bene evitare l'uso di altre funzioni all'interno delle parentesi, che potrebbe condurre a risultati errati
[source,arduino]
----
max(a--, 0);   // evita di farlo: produce risultati errati

max(a, 0);           // usa invece questo:
a--;     // mantenendo gli altri calcoli al di fuori della funzione
----

--
// HOW TO USE SECTION ENDS
