---
title: min()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= min(x, y)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Calcola il minimo di due numeri.
[%hardbreaks]


[float]
=== Sintassi
`min(x, y)`


[float]
=== Parametri
`x`: il primo numero, qualsiasi tipo di dati

`y`: il secondo numero, qualsiasi tipo di dati

[float]
=== Restituisce
Il minore dei due valori.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di esempio
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Il codice assicura che non si superi mai il valore 100.

[source,arduino]
----
sensVal = min(sensVal, 100); // assegna a sensVal il valore minore tra sensVal e 100
                             // garantendo di fatto che sia almeno 100.
----
[%hardbreaks]

[float]
=== Note e avvertenze
Per quanto possa essere controintuitivo, `max()` viene spesso utilizzato per limitare l'estremo inferiore dell'intervallo di una variabile, mentre `min()` viene utilizzato per limitare l'estremo superiore di un intervallo.

Per via del modo in cui la funzione `min()` è implementata, è bene evitare l'uso di altre funzioni all'interno delle parentesi, che potrebbe condurre a risultati errati
[source,arduino]
----
min(a++, 100);   // evita di farlo: produce risultati errati

min(a, 100);
a++;    // usa invece questo: mantenendo gli altri calcoli al di fuori della funzione
----

--
// HOW TO USE SECTION ENDS
