---
title: pow()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= pow(base, esponente)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Calcola il valore di un numero elevato a potenza. `Pow()` può essere usato per elevare un numero a una potenza frazionaria. Questo è utile per generare mappature esponenziali di valori o curve.
[%hardbreaks]


[float]
=== Sintassi
`pow(base, esponente)`


[float]
=== Parametri
`base`: il numero (`float`)

`esponente`: la potenza a cui si eleva la base (`float`)

[float]
=== Restituisce
Il risultato dell'esponenziale. (`double`)

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di esempio
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Vedi la funzione (http://arduino.cc/playground/Main/Fscale[fscale]) nella libreria dei codici.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Vedi anche

[role="definition"]
* #DEFINITION# link:../../../variables/data-types/float[float]
* #DEFENITION# link:../../../variables/data-types/double[double]

--
// SEE ALSO SECTION ENDS
