---
title: "isPunct()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isPunct(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Analizza se il carattere è un segno di interpunzione ( ovvero una virgola, punto e virgola, punto esclamativo). Restituisce 'true' se thisChar è un segno di interpunzione.
[%hardbreaks]


[float]
=== Sintassi
[source,arduino]
----
`isPunct(thisChar)`
----

[float]
=== Parametri
`thisChar`: variabile. *Tipi di dato accettati:* char

[float]
=== Restituisce
`true`: se thisChar è un segno di interpunzione.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di esempio

[source,arduino]
----
if (isPunct(this))      // tests if this is a punctuation character
{
	Serial.println("The character is a punctuation");
}
else
{
	Serial.println("The character is not a punctuation");
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Vedi anche

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
