---
title: "isWhitespace()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isWhitespace(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Analizza se un carattere è uno spazio vuoto, cioè spazio, avanzamento ('\f'), nuova linea ('\n'), ritorno a capo ('\r'), tabulazione orizzontale ('\t'), tabulazione verticale ('\v').

Restituisce 'true' se thisChar contiene uno spazio vuoto.
[%hardbreaks]


[float]
=== Sintassi
[source,arduino]
----
`isWhitespace(thisChar)`
----

[float]
=== Parametri
`thisChar`: variabile. *Tipi di dato accettati:* char

[float]
=== Restituisce
`true`: se thisChar è uno spazio vuoto.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di esempio

[source,arduino]
----
if (isWhitespace(this))      // tests if this is a white space
{
	Serial.println("The character is a white space");
}
else
{
	Serial.println("The character is not a white space");
}

----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Vedi anche

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS