---
title: costanti
categories: [ "Variabili" ]
subCategories: [ "Costanti" ]
---


= Constants


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
== Descrizione
Le constanti in Arduino sono espressioni predefinite. Vengono usate per permettere una lettura più agile del codice. Vengono classificate in gruppi:

[float]
== Definizione dei livelli logici: true e false (Costanti Booleane) 
Ci sono due costanti utilizzate per rappresentare Vero e Falso nel linguaggio Arduino: `true`, e `false`.

[float]
=== false
`false` è il modo migliore delle due opzioni per la definizione. false è definitno come 0 (zero) .
[%hardbreaks]

[float]
=== true
`true` è spesso e correttamente definito come 1, ma true ha una definizione più ampia. Qualsiasi intero che non è zero (0) è `true` (vero) in ambito booleano. quindi -1, 2 e -200 sono tutti dichiarabili come `true` (vero).
[%hardbreaks]

Notare che le costanti `true` and `false` sono scritte in minuscolo, non come HIGH`, `LOW`, `INPUT`, e `OUTPUT`.
[%hardbreaks]

[float]
== Definizione dei livelli dei Pin: HIGH e LOW
Quando bisogna leggere o scrivere un pin digitale ci sono solo due valori possibili che un pin può assumere : `HIGH` e `LOW`.

[float]
=== HIGH
Il significato di `HIGH` (riferito ad un pin) è in qualche modo differente se il pin è impostato come `INPUT` o `OUTPUT`. quando il pin è impostato come  `INPUT`  link:../../../functions/digital-io/pinmode[pinMode()], e read with link:../../../functions/digital-io/digitalread[digitalRead()],  Arduino (ATmega) riporterà `HIGH` se:

  - la tensione presente nel pin è maggiore di  3.0V (su una scheda che funziona a 5 Volt )
  - la tensione presente nel pin è maggiore di  2.0V (su una scheda che funziona a 3.3 Volt )
[%hardbreaks]

Un pin può essere impostato come un INPUT usando `pinMode()`, e successivamente impostato come HIGH usando link:../../../functions/digital-io/digitalwrite[digitalWrite()]. Questo comando abilita la resistenza di pullup da 20K, che rimarrà dale fino a quando non verrà impostata nuovamente su `LOW` da un circuito esterno. Questo è come  `INPUT_PULLUP` funziona, ed è descritto di seguito in dettaglio.

[%hardbreaks]

Quando un pin è configurato come OUTPUT usando `pinMode()`, e impostato a `HIGH` usando `digitalWrite()`, il pin risulta essere:

  - 5 volts (su schede a 5V )
  - 3.3 volts (su schede a 3.3V)

In questo stato può fornire corrente, per esempio accendere un LED connesso ad una serie di resistenze verso terra (ground).

[%hardbreaks]

[float]
=== LOW
La definizione di `LOW` ha un significato differente a seconda se un pin è impostato su `INPUT` o `OUTPUT`. Quando un pin è impostato come `INPUT` usando `pinMode()`, e letto con `digitalRead()`,  Arduino (ATmega) risulterà LOW se:
  - sul pin c'è una tensione minore di 1.5V  (su schede a 5V)
  - sul pin c'è una tensione minore di approssimativamente 1.0V (su schede a 3.3V)


When a pin is configured to `OUTPUT` with `pinMode()`, and set to `LOW` with `digitalWrite()`, the pin is at 0 volts (both 5V and 3.3V boards). In this state it can sink current, e.g. light an LED that is connected through a series resistor to +5 volts (or +3.3 volts).
[%hardbreaks]

[float]
== Definizione di Pin mode digitali: INPUT, INPUT_PULLUP, and OUTPUT
I pin digitali possono essere usati come `INPUT`, `INPUT_PULLUP`, or `OUTPUT`. Cambiando i pin usando  `pinMode()` viene cambiato il comportamento elettrico.

[float]
=== Pin configurati come INPUT
I pin delle schede Arduino basate su ATMEGA, configurate come `INPUT` usando `pinMode()`, sono in uno stato di _alta impedenza_. I Pin configurati come `INPUT` hanno pochissime necessità dal circuito che stanno campionando, equivalente ad una serie di resistenze da 100 Megohms davanti al pin. Questa condizione risulta utile quando bisogna leggere un sensore.

[%hardbreaks]


Se il pin configurato come un `INPUT`, e si sta leggendo un interruttore, quando lo switch è nello stato aperto il pin di input sarà "fluttuante", con risultati imprevedibili. Per garantire una lettura corretta quando l'interruttore è aperto, è necessario utilizzare una resistenza di pull-up o pull-down. Lo scopo di questo resistore è portare il pin in uno stato noto quando l'interruttore è aperto. Di solito viene scelta una resistenza da 10 K ohm, in quanto è un valore abbastanza basso da impedire in modo affidabile un ingresso flottante e allo stesso tempo un valore abbastanza alto da non assorbire troppa corrente quando l'interruttore è chiuso. Leggi il tutorial http://arduino.cc/en/Tutorial/DigitalReadSerial[Digital Read Serial^] per maggiori infomazioni.
[%hardbreaks]


Se viene utilizzata una resistenza pull-down, il pin di ingresso sarà `LOW` quando l'interruttore è aperto e `HIGH` quando l'interruttore è chiuso.
[% hardbreaks]

Se viene utilizzata una resistenza di pull-up, il pin di ingresso sarà `HIGH` quando l'interruttore è aperto e `LOW` quando l'interruttore è chiuso.
[% hardbreaks]


[float]


=== Pin configurati come INPUT_PULLUP
Il microcontrollore ATmega su Arduino ha resistenze interne di pull-up (resistenze che si collegano internamente all'alimentazione ) a cui si può accedere. Se si preferisce usarli al posto di resistenze di pull-up esterne, si può l'argomento `INPUT_PULLUP` in `pinMode()`.
[% hardbreaks]

Guarda il tutorial http://arduino.cc/en/Tutorial/InputPullupSerial[Input Pullup Serial^] per vedere un esempio di utilizzo.
[%hardbreaks]

 I pin configurati come ingressi con "INPUT" o "INPUT_PULLUP" possono essere danneggiati o distrutti se sono collegati a tensioni negative o sopra la soglia di alimentazione positiva (5V o 3V).
[% hardbreaks]

[float]
=== Pin configurati come OUTPUT
I pin configurati come "OUTPUT" con "pinMode ()" sono in uno stato di _ bassa impedenza_. Ciò significa che possono fornire una notevole quantità di corrente ad altri circuiti. I pin ATmega possono generare (fornire corrente) o assorbire (assorbire corrente) fino a 40 mA (milliampere) di corrente ad altri dispositivi / circuiti. Ciò li rende utili per alimentare i LED perché i LED in genere utilizzano meno di 40 mA. Carichi superiori a 40 mA (ad esempio motori) richiederanno un transistor o altri circuiti esterni di interfacciamento.
[% hardbreaks]

I pin configurati come uscite possono essere danneggiati o distrutti se sono collegati a terra o a sistemi di alimentazione positivi.
[% hardbreaks]

[float]
== Definizione di built-in: LED_BUILTIN
La maggior parte delle schede Arduino ha un pin collegato a un LED integrato in serie con un resistore. La costante `LED_BUILTIN` è il numero del pin a cui è collegato il LED di bordo. La maggior parte delle schede ha questo LED collegato al pin digitale 13.


--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

--
// HOW TO USE SECTION ENDS

// SEE ALSO  SECTION BEGINS
[#see_also]
--

[float]
=== Vedi anche

[role="language"]

--
// SEE ALSO SECTION ENDS
