---
title: if(Serial)
---




= if (Serial)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Indicates if the specified Serial port is ready.

On the Leonardo, `if (Serial)` indicates whether or not the USB CDC serial connection is open. For all other instances, including `if (Serial1)` on the Leonardo, this will always return true.

This was introduced in Arduino IDE 1.0.1.
[%hardbreaks]


[float]
=== Sintassi
_All boards:_

`if (Serial)`

_Arduino Leonardo specific:_

`if (Serial1)`

_Arduino Mega specific:_

`if (Serial1)` +
`if (Serial2)` +
`if (Serial3)`

[float]
=== Parametri
Nothing

[float]
=== Restituisce
`boolean` : returns true if the specified serial port is available. This will only return false if querying the Leonardo's USB CDC serial connection before it is ready.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Codice di Esempio
// Descrivi di quale argomento tratta il codice di esempio e aggiungi il codice relativo   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
void setup() {
 //Initialize serial and wait for port to open:
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB
  }
}

void loop() {
 //proceed normally
}
----

--
// HOW TO USE SECTION ENDS
