---
title: tone()
categories: [ "Functions" ]
subCategories: [ "I/O Avanzato" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= tone()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descrizione
Genera un'onda quadra alla frequenza specificata ( e duty cycle al 50% ) su un pin. Una durata puà essere specificata, altrimenti l'onda continua fino alla chiamata di link:../noTone[noTone()]. Il pin può essere connesso ad un buzzer piezoelettrico o altro speaker per riprodurre toni.

Solo un tono alla volta può essere generato. Se un tono è gia in riproduzione su un pin differente, la chiamata a tone() non avrà alcun effetto. Se il tono è in riproduzione sullo stesso pin, la chiamata ne imposterà la frequenza.

L'uso della funzione `tone()` interferirà con l'output PWM sui pin 3 e 11 ( sulle schede diverse dalla Mega ).

Non è possibile generare toni inferioni a 31Hz. Per i dettagli tecnici, vedi le https://github.com/bhagman/Tone#ugly-details[note di Brett Hagman].

[%hardbreaks]


[float]
=== Sintassi
`tone(pin, frequenza)`

`tone(pin, frequenza, durata)`
[%hardbreaks]

[float]
=== Parametri
`pin`: il pin sul quale generare il tono

`frequenza`: la frequenza del tono in Hertz - `unsigned int`

`durata`: la durata del tono in millisecondi (opzionale) - `unsigned long`
[%hardbreaks]

[float]
=== Restituisce
Nulla

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Note e Avvertimenti
Se vuoi riprodurre toni differenti su pin multipli, hai bisogno di chiamare `noTone()` su un pin prima di chiamare `tone()` sul pin successivo.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Vedi anche

[role="language"]
* #LINGUAGGIO# link:../../analog-io/analogwrite[analogWrite()]

[role="example"]
* #ESEMPIO# http://arduino.cc/en/Tutorial/Tone[Tone^]
* #ESEMPIO# http://arduino.cc/en/Tutorial/Tone[Pitch follower^]
* #ESEMPIO# http://arduino.cc/en/Tutorial/Tone3[Semplice Tastiera^]
* #ESEMPIO# http://arduino.cc/en/Tutorial/Tone4[Toni multipli^]
* #ESEMPIO# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// SEE ALSO SECTION ENDS
